env:
  node: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:ava/recommended'
  - 'prettier'

parserOptions:
  ecmaVersion: 2018
  sourceType: module

plugins:
  - ava

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prefer-const:
    - error
