env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module

extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'standard'
  - 'prettier'
  - 'prettier/standard'

plugins:
  - import
  - jest
  - prettier
  - standard

settings:
  import/resolver:
    'babel-module':
      root: './src'

rules:
  no-console: off
  linebreak-style:
    - error
    - unix
  prefer-const: error
  space-before-function-paren: off
  prettier/prettier: error
