env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module

plugins:
  - import
  - jest

extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'prettier'
  - 'standard'

settings:
  import/resolver:
    'babel-module':
      root: './src'

rules:
  no-console: off
  linebreak-style:
    - error
    - unix
  prefer-const:
    - error
