env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module

extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'standard'
  - 'prettier'
  - 'prettier/standard'

plugins:
  - import
  - jest

rules:
  no-console: off
  linebreak-style:
    - error
    - unix
  prefer-const: error
