language: node_js

sudo: false

node_js:
  - 8
  - stable

os:
  - linux
  - osx
  - windows

cache: npm

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

env:
  global:
    - secure: "OOot/roGPfl+dkDS2Mz1OkckNVoU8VPa1r5oJoOuQchsm9ryjjFibg/Tv/aBThkwd1yGWcheivU4nHOw+yh6Nmqfy1I01AMcQWIompuV/LOc4yYKhnA5oCMF24vYXalEkWefsSAXG45b4ZI3FxH7dTDfMt+EOWLHQCDiW0z4YKVc8/vbFDnMT3eSbMXhmlIU0YiKCp/UmifSKLGbP1AkBziuiLPpveVw4PsLD6a5JipD4auUcOlbGTf8GiZHY1Fjb1QwQMNhAeT2lgF5cT4PCMH8lqJtf9800IqySdhTfLCu8Wd1uoVyt56VzO1rypi3YIEodRKVR/vcWD0RK/abdc4pHEYp/+tUrdVqDAPM2xs8UfpwW2B7y0DoNreSWaEntuYgWmLh1ca76QSk3YbMhCcuwcGYxm/ZNrIOGJSoAUy9K+koBdezMFI3DKsiw0NYxOF3ICMPaeNTYL/mxZUd8XqQnKyheRPy9xMR4ZNrO/XfOUnab7jeheeQ28BNDDL3IZi9H/D7EIZfXDoYKE4ZrzFzKLLPj9xvcwfzQQuQ00NiW0tHXwKHBioJwEqsI6bo2ZIPxE2Cpn/LBW9n/HmHBVcgBbYSuUjv49u5I88OR46JBPA+sT1lULlX9sT3RyYKg4s1fTXitdGjp+D5y+omzzJ/wngonOz/PeaTIBHIZ40="

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

script:
  - npm run test
  - npm run doc
  - if [[ $TRAVIS_OS_NAME = linux && $TRAVIS_NODE_VERSION = 8 && $TRAVIS_BRANCH = $TRAVIS_TAG ]]; then npm run bundle; fi

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  - provider: releases
    file_glob: true
    file: "markbook-*"
    skip-cleanup: true
    api_key:
      secure: "RQApes+OcqrfbtpA12C/KB2b5RpiasWqUGM4hahLUNQF30pcRyyZEGfSvf2q4ZM9T8IMs1a+PVGfghZcrIEA/DLoxQc8AkfVv+rCU/b4qTE11jRsPaXoUll5RIZicy6H+qlvlq3t8f60w0SXw9r74rrgqEvfOygP11m9feAZwEn94VppJTmz3lb3r/TYARMMV0iirjkPihk0cdnoSrJAxdW5N+evWWyEepu4QUff2oyWRhpxKkf07CA90Hlp9lKZX3MDF/YFgIgRedAFP3P0E3Jo5s0VC/WerG6KE1WYQIcY/1EoUYs0btyf6NQJaC7zNnhDwu4tz5oSB2m8/5Fd1tp0c4kmCzwOWRWoCc3bG1GdKaf0AGbPGMkMxeqoYTKqUuxOoVFOwzPZT8TKz1HltTA0cT2i7/CnOhfsnGybJ3EoW/wJPZUBXM5q/MKxXSM9vR+C3nU31QVMuo6WZssVZJgthpNOIqS0C/GCaXp9HOoiu6++4x0vsIMyI3V7Ek6emoH1YXI2QQqXNDoj5L9kNXzLMShgtjvuR6H3o40VIgy9y4CZV/OorosOOe+BlOrc/0OMwhfRFhEjdQRXxbtkhTjZNhjdXDr6ipN57Yzu0/yBLSuv5SMmFFM/DoFXLqsL0N5Cgj3csq9fC+6dVXd4ZOQnpLDDHal2hB75+OKqa3M="
    on:
      repo: Symbitic/markbook
      branch: master
      node: '8'
      condition: $TRAVIS_OS_NAME = linux
      tags: true
  - provider: pages
    local-dir: doc/book
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      repo: Symbitic/markbook
      branch: master
      node: '8'
      condition: $TRAVIS_OS_NAME = linux
