language: node_js

sudo: false

node_js:
  - "8"
  - "10"
  - "node"

os:
  - linux
  - osx
  - windows

cache: npm

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

matrix:
  fast_finish: true

script:
  - npm run test
